spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reselling?characterEncoding=utf8&useUnicode=true&useSSL=false
      username: root
      password: password
  mail:
    host: smtp.qq.com
    username: hoshinoyukie@foxmail.com
    protocol: smtps
    password: eklsaqtftegedgaj
    port: 465
    properties:
      from: hoshinoyukie@foxmail.com
      mail:
        stmp:
          ssl:
            enable: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 12345678
  mvc:
  servlet:
    multipart:
      max-file-size: 10MB