spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.185:3306/shopping?useUnicode=true&characterEncoding=utf-8
      username: root
      password: password